# Pré-processamento 3 — Arapiraca

Este notebook transforma os dados de ocorrências em matrizes de séries temporais:
1. Carrega o CSV com índice de célula do grid
2. Calcula a hora do ano para cada ocorrência
3. Para cada tipo de crime, cria uma matriz (célula × hora) por ano
4. Agrega todos os anos e salva um CSV por tipo de crime

**Entrada:** `arapiraca_with_grid_index.csv`

**Saída:** 5 arquivos `arapiraca_{tipo_crime}_all_grid.csv`

## 1. Carregamento dos dados com índice de célula

In [1]:
# Carrega o CSV de Arapiraca com a coluna 'cell' (índice da célula do grid)
# Converte DATA_HORA para datetime

import pandas as pd

df_crimes = pd.read_csv(
    "./output/arapiraca/arapiraca_with_grid_index.csv",
    delimiter=";",
    parse_dates=["DATA_HORA"]
)

## 2. Exploração dos dados

In [2]:
display(df_crimes)
df_crimes.info()
years = sorted(df_crimes['DATA_HORA'].dt.year.unique())
display(years)

,Unnamed: 0,LONGITUDE,LATITUDE,ROUBO_GROUP,DATA_HORA,CIDADE_FATO,cell
0,0,-36.690147,-9.735983,street_robbery,2022-01-01 03:00:00,Arapiraca,2256
1,1,-36.655517,-9.785501,street_robbery,2022-01-01 20:00:00,Arapiraca,1732
2,2,-36.591520,-9.762967,vehicle_robbery,2022-01-02 09:00:00,Arapiraca,768
3,3,-36.664139,-9.768197,street_robbery,2022-01-02 23:00:00,Arapiraca,1850
4,4,-36.680604,-9.644294,street_robbery,2022-01-03 08:00:00,Arapiraca,2163
...,...,...,...,...,...,...,...
17366,17366,-36.662065,-9.764001,vehicle_robbery,2014-12-21 01:30:00,Arapiraca,1851
17367,17367,-36.666260,-9.753766,street_robbery,2014-12-22 14:30:00,Arapiraca,1910
17368,17368,-36.663400,-9.748675,street_robbery,2014-12-22 22:00:00,Arapiraca,1854
17369,17369,-36.648386,-9.721165,vehicle_robbery,2014-12-22 23:30:00,Arapiraca,1633
17370,17370,-36.632391,-9.785443,vehicle_robbery,2014-12-23 21:15:00,Arapiraca,1390

<class 'pandas.DataFrame'>
RangeIndex: 17371 entries, 0 to 17370
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   17371 non-null  int64
 1   LONGITUDE    17371 non-null  float64
 2   LATITUDE     17371 non-null  float64
 3   ROUBO_GROUP  17371 non-null  str
 4   DATA_HORA    17371 non-null  datetime64[us]
 5   CIDADE_FATO  17371 non-null  str
 6   cell         17371 non-null  int64
dtypes: datetime64[us](1), float64(2), int64(2), str(2)
memory usage: 950.1 KB

[np.int32(2012),
 np.int32(2013),
 np.int32(2014),
 np.int32(2015),
 np.int32(2016),
 np.int32(2017),
 np.int32(2018),
 np.int32(2019),
 np.int32(2020),
 np.int32(2021),
 np.int32(2022)]

## 3. Tipos de crime e intervalo temporal

In [3]:
# Identifica os tipos de crime e o intervalo de anos nos dados

crimes_types = sorted(df_crimes['ROUBO_GROUP'].unique())
display(crimes_types)

['commercial_robbery',
 'public_transport_robbery',
 'residential_robbery',
 'street_robbery',
 'vehicle_robbery']

## 4. Cálculo da hora do ano

Para cada ocorrência, calcula quantas horas se passaram desde o início do ano. Isso permite organizar os dados em uma grade temporal uniforme.

In [4]:
# Calcula a hora do ano para cada ocorrência
# Exemplo: 1 de janeiro 00:00 = hora 0, 2 de janeiro 00:00 = hora 24
# Utiliza pandarallel para processamento paralelo

import numpy as np
import datetime
from pandarallel import pandarallel
import os

cpu_count = os.cpu_count() or 1
nb_workers = max(1, min(cpu_count, 24))
pandarallel.initialize(nb_workers=nb_workers, progress_bar=True)


def hour_of_year(dt):
    beginning_of_year = datetime.datetime(
        dt["DATA_HORA"].year, 1, 1, tzinfo=dt["DATA_HORA"].tzinfo
    )
    return pd.Series(
        {
            "hour_year": (dt["DATA_HORA"] - beginning_of_year).total_seconds()
            // 3600
        }
    )


df_crimes
display("Translate date of crime to hour of the year")
df_hour = df_crimes.merge(
    df_crimes.parallel_apply(hour_of_year, axis=1), left_index=True, right_index=True
)
display("Initial shape: ", df_hour.shape)
display("Initial shape: ", df_hour)

INFO: Pandarallel will run on 24 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.

'Translate date of crime to hour of the year'

VBox(children=(HBox(children=(IntProgress(value=0, description='0.00%', max=724), Label(value='0 / 724'))), HB…

'Initial shape: '

(17371, 8)

'Initial shape: '

,Unnamed: 0,LONGITUDE,LATITUDE,ROUBO_GROUP,DATA_HORA,CIDADE_FATO,cell,hour_year
0,0,-36.690147,-9.735983,street_robbery,2022-01-01 03:00:00,Arapiraca,2256,3.0
1,1,-36.655517,-9.785501,street_robbery,2022-01-01 20:00:00,Arapiraca,1732,20.0
2,2,-36.591520,-9.762967,vehicle_robbery,2022-01-02 09:00:00,Arapiraca,768,33.0
3,3,-36.664139,-9.768197,street_robbery,2022-01-02 23:00:00,Arapiraca,1850,47.0
4,4,-36.680604,-9.644294,street_robbery,2022-01-03 08:00:00,Arapiraca,2163,56.0
...,...,...,...,...,...,...,...,...
17366,17366,-36.662065,-9.764001,vehicle_robbery,2014-12-21 01:30:00,Arapiraca,1851,8497.0
17367,17367,-36.666260,-9.753766,street_robbery,2014-12-22 14:30:00,Arapiraca,1910,8534.0
17368,17368,-36.663400,-9.748675,street_robbery,2014-12-22 22:00:00,Arapiraca,1854,8542.0
17369,17369,-36.648386,-9.721165,vehicle_robbery,2014-12-22 23:30:00,Arapiraca,1633,8543.0
17370,17370,-36.632391,-9.785443,vehicle_robbery,2014-12-23 21:15:00,Arapiraca,1390,8565.0

## 3. Tipos de crime e intervalo temporal

In [5]:
# Identifica os tipos de crime e o intervalo de anos nos dados

# Valor de GRID_SIZE calculado no notebook pre-processing-1
GRID_SIZE = 57

for ct in crimes_types:
    df_per_crime = df_hour[df_hour["ROUBO_GROUP"] == ct].copy()
    df_all_years_list = []
    for y in years:
        dfy = df_per_crime[df_per_crime["DATA_HORA"].dt.year == y].copy()

        # count crimes by (cell, DATA_HORA)
        counts = dfy.groupby(["cell", "hour_year"]).size()
        display(counts)

        grid = counts.unstack("hour_year") 


        beginning_of_y1 = datetime.datetime(y, 1, 1)
        beginning_of_y2 = datetime.datetime(y+1, 1, 1)
        num_hours_total = int((beginning_of_y2 - beginning_of_y1).total_seconds() // 3600)
        grid = grid.reindex(columns=range(num_hours_total))
        grid = grid.reindex(index=range(GRID_SIZE**2))
        df_year = grid.copy()
        df_year.columns = list(map(lambda x: str(x) + f"_{str(y)}", df_year.columns.tolist()))
        df_all_years_list.append(df_year)

  
    df_all = pd.concat(df_all_years_list,axis=1)
    df_all.T.to_csv(f"./output/arapiraca/arapiraca_{ct}_all_grid.csv")

cell  hour_year
817   1731.0       1
1339  7659.0       1
1513  7443.0       1
1563  2331.0       1
1567  2619.0       1
      2883.0       1
1568  5667.0       1
1571  3843.0       1
1573  1923.0       1
1620  4395.0       1
1680  2763.0       1
1682  2523.0       1
1736  2595.0       1
1737  2235.0       1
      2403.0       1
1738  7611.0       1
      8379.0       1
1740  243.0        2
1742  8547.0       1
1796  1707.0       1
      2403.0       1
      2643.0       1
      6675.0       1
      7155.0       1
      8307.0       1
1797  8067.0       1
1800  3171.0       1
      8595.0       1
1853  6891.0       1
      7275.0       1
      7563.0       1
1854  723.0        1
      1587.0       1
      2571.0       1
      6459.0       1
      8067.0       1
1857  315.0        1
1859  6843.0       1
1861  4011.0       1
1909  8379.0       1
1911  1803.0       1
1912  3003.0       1
1969  867.0        1
1970  51.0         1
2027  1563.0       1
2031  8019.0       1
2084  3987.0       1
2086  6459.0       1
2088  4059.0       1
      7875.0       1
2089  2619.0       1
dtype: int64

cell  hour_year
982   6833.0       1
1274  7629.0       1
1282  2102.0       1
      4104.0       1
1339  3985.0       1
                  ..
2089  6454.0       1
2142  8740.0       1
2145  8559.0       1
2201  2175.0       1
2545  3525.0       1
Length: 119, dtype: int64

cell  hour_year
1101  4480.0       1
1157  7213.0       1
1159  3668.0       1
1216  2919.0       1
1218  4101.0       1
                  ..
2089  7602.0       1
2142  2323.0       1
      2445.0       1
2145  436.0        1
2199  807.0        1
Length: 136, dtype: int64

cell  hour_year
1214  2725.0       1
1216  1753.0       1
      3017.0       1
      8683.0       1
1281  4555.0       1
                  ..
2089  1264.0       1
2140  8005.0       1
2142  7913.0       1
2146  1291.0       1
2264  3609.0       1
Length: 107, dtype: int64

cell  hour_year
239   8315.0       1
704   8315.0       1
705   2443.0       1
1098  8773.0       1
1215  8266.0       1
                  ..
2089  2130.0       1
      5685.0       1
2546  1215.0       1
2547  3279.0       1
2884  3499.0       1
Length: 153, dtype: int64

cell  hour_year
238   4810.0       1
869   5076.0       1
1155  1814.0       1
1275  1862.0       1
1387  5925.0       1
1396  5635.0       1
1453  1986.0       1
1507  1574.0       1
1510  1375.0       1
      3007.0       1
1511  829.0        1
1567  655.0        1
      1694.0       1
1570  1576.0       1
1572  115.0        1
      3183.0       1
1573  1381.0       1
1625  5822.0       1
      6016.0       1
1736  1421.0       1
1737  3240.0       1
      4238.0       1
      4865.0       1
1738  760.0        1
1740  2687.0       1
      8304.0       1
      8389.0       1
1795  1050.0       1
1796  996.0        1
      1293.0       1
      2227.0       1
      4643.0       1
      6574.0       1
1797  4365.0       1
      5755.0       1
1798  3761.0       1
1851  5680.0       1
1852  5820.0       1
      8221.0       1
1853  1359.0       1
      8125.0       1
      8393.0       1
      8508.0       1
1855  5151.0       1
1973  8325.0       1
2025  2367.0       1
2028  1379.0       1
2087  1574.0       1
      3253.0       1
      4632.0       1
2261  5299.0       1
2317  340.0        1
2323  5542.0       1
dtype: int64

cell  hour_year
1449  2542.0       1
1505  8294.0       1
1510  7705.0       1
1511  2484.0       1
1566  6348.0       1
1568  4970.0       1
1569  7977.0       1
1619  3783.0       1
1624  1327.0       1
1737  1606.0       1
1739  8684.0       1
1740  2663.0       1
1741  2254.0       1
      5230.0       1
1744  3538.0       1
      6398.0       1
1794  8628.0       1
1795  974.0        1
      2269.0       1
      3864.0       1
      5282.0       1
1796  613.0        1
      2411.0       1
      2800.0       1
      3046.0       1
      5724.0       1
      8658.0       1
1797  979.0        1
      4341.0       1
      5775.0       1
1800  1413.0       1
      3372.0       1
1851  7534.0       1
1854  2315.0       1
      8633.0       1
      8634.0       1
1909  673.0        1
      5219.0       1
1910  1480.0       1
1911  1718.0       1
      7406.0       1
1964  2490.0       1
1965  1625.0       1
1968  1293.0       1
      8489.0       1
1971  7965.0       1
1973  3210.0       1
2027  7814.0       1
2087  1667.0       1
2144  5585.0       1
2432  1148.0       2
2547  1643.0       1
dtype: int64

cell  hour_year
1216  3555.0       1
1453  1142.0       1
1456  2965.0       1
1563  6667.0       1
1626  4547.0       1
                  ..
2134  5275.0       1
2144  479.0        1
2204  4696.0       1
2478  6180.0       1
2495  2004.0       1
Length: 66, dtype: int64

cell  hour_year
1448  3525.0       1
1505  1168.0       1
1512  3591.0       1
1514  8424.0       1
1625  929.0        1
1628  7456.0       1
1684  1249.0       1
1686  7771.0       1
1730  3525.0       1
1740  7720.0       1
1794  6933.0       1
1795  6904.0       1
1796  66.0         1
      1317.0       1
      2928.0       1
      6419.0       1
      7890.0       1
      8223.0       1
1797  11.0         1
      588.0        1
      3165.0       1
      4911.0       1
      5400.0       1
1798  1723.0       1
1851  8110.0       1
1853  134.0        1
      1169.0       2
      7090.0       1
1854  307.0        1
      908.0        1
      2153.0       1
      6547.0       1
      7632.0       1
      7699.0       1
      7818.0       1
      7887.0       1
1975  354.0        1
2028  1290.0       1
      8206.0       1
2139  5604.0       1
2145  121.0        1
2255  835.0        1
2261  7485.0       1
dtype: int64

cell  hour_year
725   5041.0       1
1097  1794.0       1
1281  6953.0       1
1391  1358.0       1
1392  2491.0       1
                  ..
2198  3278.0       1
2202  3691.0       1
2255  5662.0       1
2660  5171.0       1
2717  4487.0       1
Length: 68, dtype: int64

cell  hour_year
822   4792.0       1
1449  5242.0       1
1505  153.0        1
1563  6369.0       1
1623  1317.0       1
1625  2539.0       1
1681  7623.0       1
1683  700.0        1
      3988.0       1
      4009.0       1
1732  359.0        1
1740  4489.0       1
1742  427.0        1
1794  6371.0       1
1796  3524.0       1
      4043.0       1
1797  4411.0       1
      5515.0       1
1852  4689.0       1
1853  321.0        1
      1360.0       1
      3306.0       1
      4622.0       1
      8245.0       1
1854  3011.0       1
      3042.0       1
1855  2178.0       1
1857  4434.0       1
1911  4746.0       1
1913  3103.0       1
1966  2461.0       1
1975  3882.0       1
2088  1845.0       1
2144  5443.0       1
dtype: int64

cell  hour_year
1390  3843.0       1
1916  6963.0       1
1964  4899.0       1
dtype: int64

cell  hour_year
597   8436.0       1
1041  5037.0       1
1679  589.0        1
1687  8422.0       1
1744  2896.0       1
1797  3862.0       1
      8328.0       1
1854  7175.0       1
1916  8306.0       1
1918  6311.0       1
2203  1110.0       1
dtype: int64

cell  hour_year
822   6738.0       1
989   7864.0       1
1215  8496.0       1
1274  6370.0       1
1395  6562.0       1
1854  6641.0       1
2076  7030.0       1
2483  3405.0       1
2545  6046.0       1
2547  2493.0       1
dtype: int64

cell  hour_year
519   7526.0       1
589   8037.0       1
654   3360.0       1
869   4457.0       1
879   2829.0       1
1157  4321.0       1
1215  7530.0       1
1216  8539.0       1
1390  7536.0       1
1391  8656.0       1
1732  8257.0       1
2088  3116.0       1
2317  8274.0       1
2322  286.0        1
2384  286.0        1
dtype: int64

cell  hour_year
1332  140.0        1
      475.0        1
      2326.0       1
      2445.0       1
1341  259.0        1
1391  2059.0       1
1796  6071.0       1
1797  7558.0       1
1867  5823.0       1
1909  5397.0       1
1914  5451.0       1
1917  5423.0       1
2077  1893.0       1
2088  1154.0       1
2146  6694.0       1
2242  1291.0       1
2246  112.0        1
2264  2876.0       1
      3211.0       1
      5737.0       1
      7239.0       1
      7729.0       1
2660  7650.0       1
2661  5822.0       1
dtype: int64

cell  hour_year
1111  5540.0       1
1391  3446.0       1
1399  2277.0       1
1570  4155.0       1
1625  4025.0       1
1632  5901.0       1
      6021.0       1
1917  6357.0       2
2020  2613.0       1
2077  2637.0       1
2255  3141.0       1
2264  3427.0       1
2661  3141.0       1
dtype: int64

cell  hour_year
705   3038.0       1
1216  5301.0       1
1853  2634.0       2
2306  7534.0       1
2386  4461.0       1
2420  3254.0       1
dtype: int64

cell  hour_year
868   904.0        1
932   3526.0       1
1966  6164.0       1
2147  1941.0       1
2501  6574.0       1
2603  6137.0       1
dtype: int64

cell  hour_year
1970  1895.0       1
dtype: int64

cell  hour_year
1109  765.0        1
1799  4077.0       1
2076  8244.0       1
dtype: int64

cell  hour_year
1451  4002.0       1
2265  5176.0       1
dtype: int64

cell  hour_year
1333  6459.0       1
1390  2547.0       1
1516  3939.0       1
1571  27.0         1
      5379.0       1
1682  2355.0       1
1685  7683.0       1
1687  7683.0       1
1737  195.0        1
1743  99.0         1
1795  3435.0       1
1796  6459.0       1
1850  1731.0       1
1854  5403.0       1
1860  7803.0       1
1973  915.0        1
2024  8043.0       1
2026  1491.0       1
2027  195.0        1
2028  1371.0       1
2029  1323.0       1
2089  2955.0       1
2142  3339.0       1
dtype: int64

cell  hour_year
1011  4763.0       1
1334  5223.0       1
1508  3463.0       1
1513  2382.0       1
1566  3879.0       1
1570  2115.0       1
1573  713.0        1
1621  8134.0       1
1680  7810.0       1
1682  2868.0       1
1683  6736.0       1
1738  1048.0       1
      1823.0       1
1740  3797.0       1
1743  2702.0       1
1800  2094.0       1
1963  7160.0       1
1968  3687.0       1
1969  2837.0       1
      7217.0       1
2027  8413.0       1
2084  822.0        1
2089  2351.0       1
2163  5062.0       1
2165  4660.0       1
2475  3784.0       1
dtype: int64

cell  hour_year
650   5268.0       1
932   3958.0       1
994   7632.0       1
997   8641.0       1
1051  5679.0       1
1215  7969.0       1
      8694.0       1
1274  8013.0       1
1281  4083.0       1
1332  4175.0       1
1395  7443.0       1
1562  2665.0       1
1570  5633.0       1
1622  2105.0       1
      8465.0       1
1629  2781.0       1
1674  1318.0       1
1685  35.0         1
      2218.0       1
      8723.0       1
1730  3281.0       1
1735  6353.0       1
1736  5375.0       1
1737  7150.0       1
1795  7824.0       1
1796  6622.0       1
1803  7173.0       1
1860  5056.0       1
1912  1163.0       1
2026  5857.0       1
2030  205.0        1
      6633.0       1
2087  6456.0       1
2495  6045.0       1
2540  2543.0       1
2657  1245.0       1
dtype: int64

cell  hour_year
668   8436.0       1
869   4803.0       1
1215  8618.0       1
1273  694.0        1
1274  7368.0       1
1396  7968.0       1
1505  5883.0       1
1513  160.0        1
1565  5598.0       1
1573  5746.0       1
1621  5790.0       1
1625  3039.0       1
1676  700.0        1
1680  2873.0       1
1685  1382.0       1
1736  4740.0       1
1798  3432.0       1
1842  2612.0       1
1852  1189.0       1
      3820.0       1
1855  4379.0       1
1856  3645.0       1
1857  4813.0       1
1909  4719.0       1
1913  8445.0       1
1914  7128.0       1
1919  3176.0       1
1967  5171.0       1
1969  2052.0       1
1974  7266.0       1
2027  3622.0       1
2075  7575.0       1
2086  3424.0       1
2155  7077.0       1
2256  8256.0       1
dtype: int64

cell  hour_year
296   8399.0       1
983   8325.0       1
1052  7750.0       1
1156  4673.0       1
1515  5004.0       1
1619  5050.0       1
1625  1436.0       1
1678  7007.0       1
1682  1953.0       1
1683  4983.0       1
1792  4530.0       1
1849  2525.0       1
1861  3382.0       1
1908  6099.0       1
1917  1098.0       1
      4865.0       1
1922  6743.0       1
1968  2276.0       1
1972  356.0        1
      8183.0       1
1973  8174.0       1
      8444.0       1
2024  6764.0       1
2134  7900.0       1
2140  4439.0       1
2550  977.0        1
dtype: int64

cell  hour_year
1391  4182.0       1
1453  3737.0       1
1506  2527.0       1
1509  1621.0       1
1572  5223.0       1
1732  6534.0       1
1794  2210.0       1
1798  192.0        1
      772.0        1
1799  4293.0       1
1852  6262.0       1
1853  240.0        1
1857  6984.0       1
1966  5485.0       1
1973  132.0        1
2025  8334.0       1
2087  7389.0       1
2328  4656.0       1
dtype: int64

cell  hour_year
1042  3094.0       1
1448  7643.0       1
1619  2335.0       1
1793  7536.0       1
1796  7609.0       1
1851  206.0        1
      7548.0       1
1859  8625.0       1
1896  191.0        1
1911  2024.0       1
2020  137.0        1
2025  3174.0       1
2042  4641.0       1
2432  8109.0       1
2775  8470.0       1
dtype: int64

cell  hour_year
239   71.0         1
762   4558.0       1
1216  5878.0       1
1274  6593.0       1
1335  3906.0       1
1625  618.0        1
      992.0        1
1627  2702.0       1
1794  1992.0       1
1796  3827.0       1
1797  7411.0       1
1855  1768.0       1
1860  5015.0       1
1915  471.0        1
1966  186.0        1
1968  8145.0       1
2142  2491.0       1
2602  7145.0       1
dtype: int64

cell  hour_year
115   2209.0       1
822   1968.0       1
869   2232.0       1
1513  7328.0       1
1517  819.0        1
1628  6708.0       1
1793  7271.0       1
1854  1218.0       1
1917  1558.0       1
2083  2326.0       1
2360  75.0         1
dtype: int64

cell  hour_year
597   2151.0       1
1265  3386.0       1
1266  4966.0       1
1283  83.0         1
1451  166.0        1
1506  5314.0       1
1530  455.0        1
1623  8722.0       1
1625  7347.0       1
1629  3888.0       1
1682  1263.0       1
1697  1120.0       1
1741  49.0         1
1795  2458.0       1
      7702.0       1
1798  6751.0       1
1851  5332.0       1
1852  7035.0       1
1853  2446.0       1
1854  1691.0       1
      5214.0       1
      5761.0       1
1856  2140.0       1
1910  845.0        1
      2669.0       1
1975  8102.0       1
1976  3262.0       1
2083  670.0        1
2093  359.0        1
2149  191.0        1
2255  3242.0       1
2662  3554.0       1
dtype: int64

cell  hour_year
647   4874.0       1
1738  5137.0       1
1911  4030.0       1
2029  3154.0       1
2147  4317.0       1
dtype: int64

cell  hour_year
597   1755.0       1
      1995.0       1
668   7851.0       1
1274  3987.0       1
1331  8403.0       1
                  ..
2144  1923.0       1
      5379.0       1
2147  363.0        1
2199  4923.0       1
2359  6339.0       1
Length: 310, dtype: int64

cell  hour_year
426   3746.0       1
522   5753.0       1
704   1965.0       1
      7870.0       1
761   5353.0       1
                  ..
2495  5929.0       1
2540  6404.0       1
2603  5301.0       1
2831  5109.0       1
2889  4342.0       1
Length: 515, dtype: int64

cell  hour_year
590   4202.0       1
596   3320.0       1
653   816.0        1
654   7514.0       1
762   7174.0       1
                  ..
2716  887.0        1
2773  4151.0       1
2829  1145.0       1
      7153.0       1
2888  1617.0       1
Length: 737, dtype: int64

cell  hour_year
403   6783.0       1
464   5533.0       1
597   1942.0       1
654   2038.0       1
      8026.0       1
                  ..
2775  347.0        1
2883  7974.0       1
      8734.0       1
2884  7974.0       1
2941  7438.0       1
Length: 1153, dtype: int64

cell  hour_year
370   4558.0       1
      4941.0       1
      6113.0       1
407   8315.0       1
410   7608.0       1
                  ..
2885  3098.0       1
2889  2773.0       1
2941  3100.0       1
      4443.0       1
3003  8107.0       1
Length: 1725, dtype: int64

cell  hour_year
239   4876.0       1
295   180.0        1
296   262.0        1
      4459.0       1
344   381.0        1
                  ..
2888  88.0         1
      278.0        1
      3986.0       1
2941  3624.0       1
      8254.0       1
Length: 1216, dtype: int64

cell  hour_year
296   4880.0       1
402   7403.0       1
461   2537.0       1
475   971.0        1
579   1015.0       1
                  ..
2884  250.0        1
      3312.0       1
      5348.0       1
2941  5808.0       1
3116  525.0        1
Length: 966, dtype: int64

cell  hour_year
297   2842.0       1
305   6900.0       1
370   3032.0       1
403   5482.0       1
462   1001.0       1
                  ..
2717  280.0        1
      2424.0       1
      5711.0       1
2775  693.0        1
2946  135.0        1
Length: 830, dtype: int64

cell  hour_year
239   2985.0       1
410   5653.0       1
588   8120.0       1
591   1097.0       1
704   1593.0       1
                  ..
2717  7863.0       1
2826  5024.0       1
2831  1003.0       1
2883  2539.0       1
3174  1808.0       1
Length: 550, dtype: int64

cell  hour_year
239   8058.0       1
345   7911.0       1
519   467.0        1
540   5632.0       1
590   3742.0       1
                  ..
2660  8109.0       1
2717  1762.0       1
      4892.0       1
2773  1257.0       1
2829  327.0        1
Length: 764, dtype: int64

cell  hour_year
363   1041.0       1
461   2459.0       1
654   3612.0       1
724   2560.0       1
      5248.0       1
                  ..
2490  3632.0       1
2491  4332.0       1
2552  4939.0       1
2602  3929.0       1
2660  4998.0       1
Length: 624, dtype: int64

cell  hour_year
237   2379.0       1
299   627.0        1
369   5163.0       1
370   6459.0       1
406   6915.0       1
                  ..
2301  2643.0       1
2359  4131.0       1
2382  4155.0       1
2500  2139.0       1
2661  5475.0       1
Length: 446, dtype: int64

cell  hour_year
232   6632.0       1
239   6215.0       1
610   4871.0       1
654   7322.0       1
668   1856.0       1
                  ..
2831  3877.0       1
2884  5064.0       1
2888  5840.0       1
3001  5851.0       1
3006  3716.0       1
Length: 594, dtype: int64

cell  hour_year
401   563.0        1
      616.0        1
402   910.0        1
483   8729.0       1
532   5605.0       1
                  ..
2773  7482.0       1
2830  1599.0       1
2832  8254.0       1
2889  8017.0       1
2943  193.0        1
Length: 890, dtype: int64

cell  hour_year
287   6405.0       1
351   1240.0       1
589   7776.0       1
597   38.0         1
      2038.0       1
                  ..
2836  6141.0       1
2884  1616.0       1
2941  8447.0       1
2951  3059.0       1
3060  4492.0       1
Length: 831, dtype: int64

cell  hour_year
185   7414.0       1
370   3216.0       1
      6117.0       1
418   184.0        1
538   3887.0       1
                  ..
2884  633.0        1
      3100.0       1
      8642.0       1
2941  409.0        1
      4128.0       1
Length: 1000, dtype: int64

cell  hour_year
176   813.0        1
238   4678.0       1
239   4876.0       1
294   6454.0       1
296   1128.0       1
                  ..
2884  6388.0       1
2890  3440.0       1
2894  493.0        1
2946  4101.0       1
2948  6572.0       1
Length: 599, dtype: int64

cell  hour_year
296   3088.0       1
410   8158.0       1
426   4002.0       1
518   1561.0       1
590   978.0        1
                  ..
2889  7362.0       1
2940  4077.0       1
2946  4511.0       1
3060  7887.0       1
3116  819.0        1
Length: 917, dtype: int64

cell  hour_year
461   3410.0       1
      6445.0       1
519   337.0        1
588   5635.0       1
      8445.0       1
                  ..
2831  8739.0       1
2883  1824.0       1
      2420.0       1
2888  4221.0       1
2951  5249.0       1
Length: 488, dtype: int64

cell  hour_year
0     3214.0       1
239   7049.0       1
254   860.0        1
363   3131.0       1
530   3946.0       1
                  ..
2717  2554.0       1
2883  8636.0       1
2884  8544.0       1
2941  885.0        1
3003  2520.0       1
Length: 307, dtype: int64

cell  hour_year
239   2738.0       1
295   6406.0       1
403   785.0        1
410   1390.0       1
461   118.0        1
                  ..
2831  6166.0       1
2883  6290.0       1
2884  865.0        1
      3838.0       1
      7534.0       1
Length: 347, dtype: int64

cell  hour_year
239   1190.0       1
645   3656.0       1
704   546.0        1
724   3474.0       1
768   33.0         1
                  ..
2720  5075.0       1
2775  3316.0       1
2831  4567.0       1
2884  4020.0       1
2951  2219.0       1
Length: 244, dtype: int64