# Pré-processamento 3 — Maceió

Este notebook transforma os dados de ocorrências em matrizes de séries temporais:
1. Carrega o CSV com índice de célula do grid
2. Calcula a hora do ano para cada ocorrência
3. Para cada tipo de crime, cria uma matriz (célula × hora) por ano
4. Agrega todos os anos e salva um CSV por tipo de crime

**Entrada:** `maceio_with_grid_index.csv`

**Saída:** 5 arquivos `maceio_{tipo_crime}_all_grid.csv`

## 1. Carregamento dos dados com índice de célula

In [6]:
# Carrega o CSV de Maceió com a coluna 'cell' (índice da célula do grid)
# Converte DATA_HORA para datetime

import pandas as pd

df_crimes = pd.read_csv(
    "./output/maceio/maceio_with_grid_index.csv",
    delimiter=";",
    parse_dates=["DATA_HORA"]
)

## 2. Exploração dos dados

In [7]:
display(df_crimes)
df_crimes.info()
years = sorted(df_crimes['DATA_HORA'].dt.year.unique())
display(years)

,Unnamed: 0,LONGITUDE,LATITUDE,ROUBO_GROUP,DATA_HORA,CIDADE_FATO,cell
0,0,-35.698388,-9.658217,street_robbery,2022-01-01 02:00:00,Maceió,2858
1,1,-35.703405,-9.660662,street_robbery,2022-01-01 02:00:00,Maceió,3004
2,2,-35.710142,-9.653007,vehicle_robbery,2022-01-01 02:00:00,Maceió,3151
3,3,-35.713147,-9.668955,street_robbery,2022-01-01 03:00:00,Maceió,3221
4,4,-35.703983,-9.663635,street_robbery,2022-01-01 04:00:00,Maceió,3003
...,...,...,...,...,...,...,...
72707,72707,-35.756315,-9.662037,street_robbery,2014-12-22 12:50:00,Maceió,4098
72708,72708,-35.715706,-9.652401,vehicle_robbery,2014-12-22 19:00:00,Maceió,3224
72709,72709,-35.755908,-9.586733,residential_robbery,2014-12-23 05:30:00,Maceió,4114
72710,72710,-35.738317,-9.624963,street_robbery,2014-12-23 09:30:00,Maceió,3741
72711,72711,-35.739418,-9.630707,vehicle_robbery,2014-12-23 15:00:00,Maceió,3740

<class 'pandas.DataFrame'>
RangeIndex: 72712 entries, 0 to 72711
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   72712 non-null  int64
 1   LONGITUDE    72712 non-null  float64
 2   LATITUDE     72712 non-null  float64
 3   ROUBO_GROUP  72712 non-null  str
 4   DATA_HORA    72712 non-null  datetime64[us]
 5   CIDADE_FATO  72712 non-null  str
 6   cell         72712 non-null  int64
dtypes: datetime64[us](1), float64(2), int64(2), str(2)
memory usage: 3.9 MB

[np.int32(2012),
 np.int32(2013),
 np.int32(2014),
 np.int32(2015),
 np.int32(2016),
 np.int32(2017),
 np.int32(2018),
 np.int32(2019),
 np.int32(2020),
 np.int32(2021),
 np.int32(2022)]

## 3. Tipos de crime e intervalo temporal

In [8]:
# Identifica os tipos de crime e o intervalo de anos nos dados

crimes_types = sorted(df_crimes['ROUBO_GROUP'].unique())
display(crimes_types)

['commercial_robbery',
 'public_transport_robbery',
 'residential_robbery',
 'street_robbery',
 'vehicle_robbery']

## 4. Cálculo da hora do ano

Para cada ocorrência, calcula quantas horas se passaram desde o início do ano. Isso permite organizar os dados em uma grade temporal uniforme.

In [9]:
# Calcula a hora do ano para cada ocorrência
# Exemplo: 1 de janeiro 00:00 = hora 0, 2 de janeiro 00:00 = hora 24
# Utiliza pandarallel para processamento paralelo

import numpy as np
import datetime
from pandarallel import pandarallel
import os

cpu_count = os.cpu_count() or 1
nb_workers = max(1, min(cpu_count, 24))
pandarallel.initialize(nb_workers=nb_workers, progress_bar=True)


def hour_of_year(dt):
    beginning_of_year = datetime.datetime(
        dt["DATA_HORA"].year, 1, 1, tzinfo=dt["DATA_HORA"].tzinfo
    )
    return pd.Series(
        {
            "hour_year": (dt["DATA_HORA"] - beginning_of_year).total_seconds()
            // 3600
        }
    )


df_crimes
display("Translate date of crime to hour of the year")
df_hour = df_crimes.merge(
    df_crimes.parallel_apply(hour_of_year, axis=1), left_index=True, right_index=True
)
display("Initial shape: ", df_hour.shape)
display("Initial shape: ", df_hour)

INFO: Pandarallel will run on 24 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.

'Translate date of crime to hour of the year'

VBox(children=(HBox(children=(IntProgress(value=0, description='0.00%', max=3030), Label(value='0 / 3030'))), …

'Initial shape: '

(72712, 8)

'Initial shape: '

,Unnamed: 0,LONGITUDE,LATITUDE,ROUBO_GROUP,DATA_HORA,CIDADE_FATO,cell,hour_year
0,0,-35.698388,-9.658217,street_robbery,2022-01-01 02:00:00,Maceió,2858,2.0
1,1,-35.703405,-9.660662,street_robbery,2022-01-01 02:00:00,Maceió,3004,2.0
2,2,-35.710142,-9.653007,vehicle_robbery,2022-01-01 02:00:00,Maceió,3151,2.0
3,3,-35.713147,-9.668955,street_robbery,2022-01-01 03:00:00,Maceió,3221,3.0
4,4,-35.703983,-9.663635,street_robbery,2022-01-01 04:00:00,Maceió,3003,4.0
...,...,...,...,...,...,...,...,...
72707,72707,-35.756315,-9.662037,street_robbery,2014-12-22 12:50:00,Maceió,4098,8532.0
72708,72708,-35.715706,-9.652401,vehicle_robbery,2014-12-22 19:00:00,Maceió,3224,8539.0
72709,72709,-35.755908,-9.586733,residential_robbery,2014-12-23 05:30:00,Maceió,4114,8549.0
72710,72710,-35.738317,-9.624963,street_robbery,2014-12-23 09:30:00,Maceió,3741,8553.0
72711,72711,-35.739418,-9.630707,vehicle_robbery,2014-12-23 15:00:00,Maceió,3740,8559.0

## 3. Tipos de crime e intervalo temporal

In [10]:
# Identifica os tipos de crime e o intervalo de anos nos dados

GRID_SIZE = 73

for ct in crimes_types:
    df_per_crime = df_hour[df_hour["ROUBO_GROUP"] == ct].copy()
    df_all_years_list = []
    for y in years:
        dfy = df_per_crime[df_per_crime["DATA_HORA"].dt.year == y].copy()

        # count crimes by (cell, DATA_HORA)
        counts = dfy.groupby(["cell", "hour_year"]).size()
        display(counts)

        grid = counts.unstack("hour_year") 


        beginning_of_y1 = datetime.datetime(y, 1, 1)
        beginning_of_y2 = datetime.datetime(y+1, 1, 1)
        num_hours_total = int((beginning_of_y2 - beginning_of_y1).total_seconds() // 3600)
        grid = grid.reindex(columns=range(num_hours_total))
        grid = grid.reindex(index=range(GRID_SIZE**2))
        df_year = grid.copy()
        df_year.columns = list(map(lambda x: str(x) + f"_{str(y)}", df_year.columns.tolist()))
        df_all_years_list.append(df_year)

  
    df_all = pd.concat(df_all_years_list,axis=1)
    df_all.T.to_csv(f"./output/maceio/maceio_{ct}_all_grid.csv")

cell  hour_year
1277  6891.0       1
2520  963.0        1
      1443.0       1
      4035.0       1
      4923.0       1
                  ..
4564  1587.0       1
      1971.0       1
      6171.0       1
4780  579.0        1
      4059.0       1
Length: 365, dtype: int64

cell  hour_year
412   5857.0       1
556   6964.0       1
844   3984.0       1
916   4297.0       1
1784  7493.0       1
                  ..
4781  5395.0       1
4783  5395.0       1
      7285.0       1
4848  7910.0       1
4991  1054.0       1
Length: 812, dtype: int64

cell  hour_year
701   6865.0       1
1783  825.0        1
2000  8414.0       1
2073  107.0        1
2144  6429.0       1
                  ..
4855  1096.0       1
4929  1984.0       1
4991  1717.0       1
5001  2175.0       1
      4118.0       1
Length: 600, dtype: int64

cell  hour_year
701   973.0        1
987   8737.0       1
988   3265.0       1
2000  6927.0       1
2144  7099.0       1
                  ..
4848  4034.0       1
4849  574.0        1
4854  5106.0       1
4929  6625.0       1
4991  522.0        1
Length: 310, dtype: int64

cell  hour_year
267   4316.0       1
988   117.0        1
1784  5611.0       1
2001  2830.0       1
      2974.0       1
                  ..
4781  6228.0       1
4782  8708.0       1
4783  4461.0       1
4928  8566.0       1
5212  7837.0       1
Length: 334, dtype: int64

cell  hour_year
844   1794.0       1
2001  2441.0       1
      7582.0       1
2931  3755.0       1
2932  6059.0       1
                  ..
4781  51.0         1
      7145.0       2
4782  3563.0       1
4855  8643.0       1
4992  7485.0       1
Length: 248, dtype: int64

cell  hour_year
1277  3095.0       1
2722  1525.0       1
2794  578.0        1
2864  1384.0       1
2936  70.0         1
                  ..
4782  1747.0       1
4783  4509.0       1
4848  569.0        1
4929  4679.0       1
      8523.0       1
Length: 197, dtype: int64

cell  hour_year
2931  1801.0       1
3003  8404.0       1
3005  2104.0       2
3007  2271.0       1
      3327.0       1
                  ..
4782  4285.0       1
4846  1530.0       1
4855  2682.0       1
      7533.0       1
4921  7317.0       1
Length: 173, dtype: int64

cell  hour_year
2072  2562.0       1
2217  5132.0       1
2937  624.0        1
3007  6748.0       1
      6772.0       1
                  ..
4781  6060.0       1
      6180.0       1
      7428.0       1
4782  7580.0       1
4853  6564.0       1
Length: 93, dtype: int64

cell  hour_year
484   1253.0       1
2722  979.0        1
2857  7481.0       1
2930  3864.0       1
      4870.0       1
                  ..
4776  2376.0       1
4779  4217.0       1
4781  2369.0       1
      4674.0       1
4784  8173.0       1
Length: 178, dtype: int64

cell  hour_year
2144  7531.0       1
2863  2459.0       1
      5349.0       1
2932  243.0        1
      411.0        1
                  ..
4778  4648.0       1
      4725.0       1
4781  4459.0       1
4784  7722.0       1
4848  1026.0       1
Length: 99, dtype: int64

cell  hour_year
1133  3987.0       1
1277  1299.0       1
2505  1203.0       1
2520  363.0        1
      435.0        1
                  ..
4995  6627.0       1
5066  8619.0       1
5211  1995.0       1
      7011.0       1
5212  5523.0       1
Length: 630, dtype: int64

cell  hour_year
339   7340.0       1
843   5952.0       1
988   5786.0       1
1206  5442.0       1
1856  7029.0       1
                  ..
5065  8470.0       1
5067  7166.0       1
5211  7101.0       1
5212  5241.0       1
5213  3875.0       1
Length: 1011, dtype: int64

cell  hour_year
339   382.0        1
      5829.0       1
628   1601.0       1
      5857.0       1
629   7142.0       1
                  ..
4991  5637.0       1
      5687.0       1
5064  235.0        1
5138  6937.0       1
5212  2784.0       1
Length: 1206, dtype: int64

cell  hour_year
339   2519.0       1
628   1827.0       1
      7339.0       1
701   1885.0       1
771   6614.0       1
                  ..
4849  7272.0       1
4917  217.0        1
4929  3742.0       1
      6909.0       1
      7125.0       1
Length: 788, dtype: int64

cell  hour_year
269   2445.0       1
628   4485.0       1
1783  2354.0       1
      5959.0       1
1784  2092.0       1
                  ..
4929  4196.0       1
4990  8556.0       1
4991  3267.0       1
5064  3145.0       1
5138  6374.0       1
Length: 1139, dtype: int64

cell  hour_year
988   2710.0       1
1494  96.0         1
      1490.0       1
1783  6262.0       1
1784  601.0        1
                  ..
4921  1548.0       1
4929  2349.0       1
4991  2349.0       1
      6424.0       1
5214  8755.0       1
Length: 534, dtype: int64

cell  hour_year
1494  1458.0       1
1783  5111.0       1
2000  1840.0       1
2144  1792.0       1
      2276.0       1
                  ..
4848  7152.0       1
4853  5278.0       1
4917  1959.0       1
4929  6403.0       1
4991  5594.0       1
Length: 340, dtype: int64

cell  hour_year
1494  7809.0       1
2217  7344.0       1
2433  4030.0       1
2650  2135.0       1
3079  8059.0       1
                  ..
4777  4941.0       1
4781  375.0        1
      432.0        1
4922  5962.0       1
5141  5916.0       1
Length: 109, dtype: int64

cell  hour_year
3303  2126.0       1
3370  10.0         1
3382  1800.0       1
3440  512.0        1
3441  2099.0       1
      7776.0       1
3443  1198.0       1
3514  2194.0       1
3515  1582.0       1
3520  3395.0       1
3522  1271.0       1
3586  8760.0       1
3588  8569.0       1
3589  2292.0       1
3595  519.0        1
      1360.0       1
3659  2254.0       1
      8401.0       1
3660  8544.0       1
3661  8449.0       1
3662  2292.0       1
3664  1247.0       1
3665  769.0        1
3733  2087.0       1
      2133.0       1
      2137.0       1
      8688.0       1
3734  2061.0       1
3735  2061.0       1
      2113.0       1
3745  109.0        1
3752  418.0        1
3805  2296.0       1
3806  1968.0       1
3818  3575.0       1
3887  1605.0       1
3951  2443.0       1
3958  1290.0       1
4098  1760.0       1
4172  3130.0       1
4260  1273.0       1
4484  322.0        1
4701  679.0        1
      937.0        1
4853  888.0        1
      5888.0       1
dtype: int64

cell  hour_year
3226  1079.0       1
      1223.0       1
      6599.0       1
3298  7602.0       1
3442  1129.0       1
3443  912.0        1
3586  697.0        1
      983.0        1
      1031.0       1
3587  908.0        1
      1369.0       2
      1679.0       1
      7626.0       1
3588  48.0         1
3590  5147.0       1
3612  6479.0       1
3659  4941.0       1
3660  1750.0       1
3661  8470.0       1
3664  5087.0       1
      5133.0       1
3732  1031.0       1
3748  1920.0       1
3751  6023.0       1
3806  1008.0       1
3818  4911.0       1
3952  1008.0       1
      1824.0       1
4098  1848.0       1
      3385.0       1
4187  5177.0       1
4261  5560.0       1
dtype: int64

cell  hour_year
3154  8173.0       1
3170  4654.0       1
3221  6563.0       1
      8341.0       1
3228  5218.0       1
3308  7859.0       1
3316  1496.0       1
3393  7371.0       1
3464  8182.0       1
3537  8220.0       1
3586  8556.0       1
3587  716.0        1
3661  6830.0       1
3733  1638.0       1
3734  4164.0       1
3743  8701.0       1
3809  7982.0       1
3818  132.0        1
      8373.0       1
3819  273.0        1
3973  4541.0       1
4040  4915.0       1
4116  8699.0       1
4705  8676.0       1
4849  8455.0       1
5214  4573.0       1
dtype: int64

cell  hour_year
2075  4467.0       1
2511  4059.0       1
      8739.0       1
2520  3555.0       1
      5883.0       1
                  ..
4262  8043.0       1
4344  2523.0       1
4484  1107.0       1
      1731.0       1
      4611.0       1
Length: 113, dtype: int64

cell  hour_year
844   2704.0       1
2721  3661.0       1
      7821.0       1
      7839.0       1
2865  6228.0       1
                  ..
4775  491.0        1
      6405.0       1
4783  3520.0       1
      5827.0       1
4856  340.0        1
Length: 161, dtype: int64

cell  hour_year
2074  6358.0       1
2722  8290.0       1
2865  3185.0       1
2932  7075.0       1
2936  6717.0       1
                  ..
4708  2427.0       1
4709  4049.0       1
4778  5922.0       1
4782  3075.0       1
4783  6782.0       1
Length: 132, dtype: int64

cell  hour_year
1712  5403.0       1
2721  288.0        1
2864  2560.0       1
2931  4431.0       1
3007  5432.0       1
                  ..
4780  1304.0       1
4781  8241.0       1
      8448.0       1
4782  7918.0       1
5138  7212.0       1
Length: 94, dtype: int64

cell  hour_year
339   610.0        1
987   662.0        1
1857  2231.0       1
2074  6621.0       1
2146  20.0         1
                  ..
4708  94.0         1
4780  6093.0       1
4781  6681.0       1
4783  1552.0       1
4784  1653.0       1
Length: 123, dtype: int64

cell  hour_year
916   5206.0       1
2074  7143.0       1
2144  7353.0       1
2505  373.0        1
2649  374.0        1
                  ..
4779  3536.0       1
4780  743.0        1
4782  6648.0       1
4852  4092.0       1
5001  4239.0       1
Length: 83, dtype: int64

cell  hour_year
1061  3022.0       1
2072  1201.0       1
2217  3069.0       1
2218  2563.0       1
2289  4641.0       1
                  ..
4848  7849.0       1
4853  3748.0       1
4855  8159.0       1
4929  4647.0       1
4992  6645.0       1
Length: 133, dtype: int64

cell  hour_year
701   5926.0       1
2292  7284.0       1
2506  3000.0       1
2507  3000.0       1
2723  7581.0       1
                  ..
4774  4844.0       1
4848  297.0        1
      2189.0       1
      5841.0       1
5065  3606.0       1
Length: 76, dtype: int64

cell  hour_year
2292  724.0        1
3009  1225.0       1
3013  7446.0       1
3021  511.0        1
3221  471.0        1
3244  2093.0       1
3245  2638.0       1
3294  5167.0       1
3295  7238.0       1
3315  2377.0       1
      7943.0       1
3374  5978.0       1
3388  839.0        1
      7032.0       1
3389  2282.0       1
3390  7389.0       1
3391  1941.0       1
3463  1435.0       1
3589  3485.0       1
3739  856.0        1
3810  7373.0       1
3824  7675.0       1
3832  2811.0       1
3879  62.0         1
      461.0        1
3903  7943.0       1
3905  8690.0       1
3950  6534.0       1
3978  7898.0       1
4036  1777.0       1
4046  2926.0       1
4051  8718.0       1
4100  298.0        1
4107  3185.0       1
4116  1774.0       1
      7840.0       1
4125  5362.0       1
4172  462.0        1
4188  2407.0       1
4246  7222.0       1
4404  575.0        1
4407  338.0        1
4564  5596.0       1
4702  8620.0       1
4703  919.0        1
4708  448.0        1
4782  6908.0       1
      7062.0       1
4783  8017.0       1
4784  1254.0       1
4848  7919.0       1
4992  1003.0       1
      2023.0       2
dtype: int64

cell  hour_year
2000  2159.0       1
3080  7373.0       1
3223  3825.0       1
3228  3768.0       1
3229  677.0        1
      4232.0       1
3231  1479.0       1
3244  4319.0       1
      4750.0       1
3295  1750.0       1
3306  3741.0       1
3307  5186.0       1
3366  1576.0       1
3368  1103.0       1
3378  4256.0       1
3388  1014.0       1
      5614.0       1
3392  1918.0       1
3393  384.0        1
3441  670.0        1
3463  7846.0       1
3466  385.0        1
      5279.0       1
3537  2925.0       1
3592  7231.0       1
3611  7830.0       1
3745  573.0        1
3759  1590.0       1
3828  2818.0       1
3903  5560.0       1
      8720.0       1
3951  748.0        1
3952  2999.0       1
3953  5023.0       1
4044  1426.0       1
4099  2008.0       2
4107  92.0         1
      5652.0       1
4117  5943.0       1
4170  2781.0       1
4173  6829.0       1
4189  1822.0       1
      4750.0       1
4244  1241.0       1
4261  8181.0       1
4270  2805.0       1
4318  6293.0       1
4336  645.0        1
4406  6293.0       1
4409  5938.0       1
4458  7566.0       1
4479  3330.0       1
4490  4647.0       1
4624  4798.0       1
4626  3084.0       1
4700  1962.0       1
      2312.0       1
4775  5989.0       1
4783  6796.0       1
4856  3479.0       1
dtype: int64

cell  hour_year
1783  4889.0       1
2217  3032.0       1
2938  1018.0       1
3156  4963.0       1
3157  1943.0       1
3169  8195.0       1
3228  5322.0       1
3245  6284.0       1
3320  5812.0       1
3372  2019.0       1
3386  6475.0       1
      7532.0       1
3387  5180.0       1
      6141.0       1
3390  2215.0       1
      6764.0       1
3393  4113.0       1
3451  2101.0       1
3461  3926.0       1
3463  3548.0       1
3465  3764.0       1
3467  4694.0       1
3523  8178.0       1
3537  6.0          1
3538  2066.0       1
3609  3285.0       1
3733  5899.0       1
3745  5345.0       1
3808  1748.0       1
3879  2628.0       1
3952  3932.0       1
3977  4292.0       1
4042  5459.0       1
4050  2185.0       1
4100  2458.0       1
4116  3082.0       1
4170  4780.0       1
4189  6843.0       1
4191  4780.0       2
4242  1326.0       1
4270  1846.0       1
      6856.0       1
4333  594.0        1
4563  2513.0       1
4701  1209.0       1
4773  6166.0       1
5212  7209.0       1
dtype: int64

cell  hour_year
770   795.0        1
      7635.0       1
771   5139.0       1
2000  5835.0       1
2002  8091.0       1
                  ..
4995  1467.0       1
5001  3147.0       1
      3795.0       1
5211  195.0        2
      5163.0       1
Length: 2975, dtype: int64

cell  hour_year
411   7503.0       1
412   2234.0       1
626   8540.0       1
628   8370.0       1
699   3180.0       1
                  ..
4991  8125.0       1
4994  7625.0       1
5001  7448.0       1
5065  5447.0       1
5214  6304.0       1
Length: 3969, dtype: int64

cell  hour_year
339   7583.0       1
626   856.0        1
701   6756.0       1
      7432.0       1
988   2420.0       1
                  ..
5001  4166.0       1
5065  2667.0       1
      4895.0       1
5138  6284.0       1
5212  4821.0       1
Length: 4977, dtype: int64

cell  hour_year
120   2417.0       1
628   1964.0       1
      8169.0       1
701   4347.0       1
772   8448.0       1
                  ..
5001  8300.0       1
5064  1920.0       1
5065  474.0        1
5213  5313.0       1
      8125.0       1
Length: 5044, dtype: int64

cell  hour_year
47    3255.0       1
121   3231.0       1
484   839.0        1
554   1911.0       1
628   2392.0       1
                  ..
5212  4918.0       1
      6392.0       1
5213  2481.0       1
5284  7368.0       1
5285  7967.0       1
Length: 6110, dtype: int64

cell  hour_year
192   8348.0       1
339   2736.0       1
      6361.0       1
628   7280.0       1
700   1585.0       1
                  ..
5212  7579.0       1
      7755.0       1
5285  957.0        1
      5351.0       1
5286  5632.0       1
Length: 6580, dtype: int64

cell  hour_year
339   37.0         1
      327.0        1
      7752.0       1
484   4792.0       1
557   6253.0       1
                  ..
5214  3418.0       1
      3999.0       1
      4790.0       1
      6897.0       1
5285  6503.0       1
Length: 6459, dtype: int64

cell  hour_year
194   4551.0       1
339   8160.0       1
340   3329.0       1
484   6536.0       1
628   8377.0       1
                  ..
5140  6022.0       1
      8720.0       1
5212  5927.0       1
      6373.0       1
5214  4545.0       1
Length: 5049, dtype: int64

cell  hour_year
194   776.0        1
337   5609.0       1
339   8011.0       1
484   776.0        1
628   1544.0       2
                  ..
5212  1057.0       1
      1572.0       1
      2204.0       1
      2360.0       1
5214  560.0        1
Length: 3685, dtype: int64

cell  hour_year
194   2223.0       1
339   311.0        1
      3256.0       1
628   2115.0       1
      3452.0       1
                  ..
4930  4833.0       1
5212  4561.0       1
5284  7215.0       1
      8750.0       1
5285  2743.0       1
Length: 2936, dtype: int64

cell  hour_year
340   1359.0       1
628   3445.0       1
915   8461.0       1
989   6320.0       1
1061  4976.0       1
                  ..
5211  4688.0       1
5212  5867.0       1
      6746.0       1
5213  5940.0       1
      6104.0       1
Length: 2939, dtype: int64

cell  hour_year
770   2379.0       1
      2739.0       1
771   1923.0       1
      4707.0       1
843   8115.0       1
                  ..
4924  7611.0       1
4990  843.0        1
4993  387.0        1
4995  627.0        1
5213  2907.0       1
Length: 1525, dtype: int64

cell  hour_year
340   3410.0       1
413   5206.0       1
701   8685.0       1
770   1840.0       1
843   988.0        1
                  ..
5067  2712.0       1
5211  1513.0       1
5212  277.0        1
      8421.0       1
5213  6684.0       1
Length: 1530, dtype: int64

cell  hour_year
120   5756.0       1
266   3334.0       1
268   2014.0       1
339   938.0        1
628   3648.0       1
                  ..
5138  6979.0       1
5212  553.0        1
      3237.0       1
5213  6112.0       1
5285  2206.0       1
Length: 1535, dtype: int64

cell  hour_year
194   5540.0       1
267   7027.0       1
269   672.0        1
412   7269.0       1
628   2052.0       1
                  ..
5001  7404.0       1
5064  1361.0       1
5212  7344.0       1
5213  3405.0       1
5214  5341.0       1
Length: 1060, dtype: int64

cell  hour_year
413   7851.0       1
698   3740.0       1
844   8660.0       1
988   5426.0       1
1062  8321.0       1
                  ..
4993  3278.0       1
5065  3838.0       1
5138  6745.0       1
5212  3158.0       1
      6360.0       1
Length: 1219, dtype: int64

cell  hour_year
700   5212.0       1
701   3959.0       1
915   8346.0       1
987   1866.0       2
1494  1512.0       1
                  ..
5211  7920.0       1
5212  6648.0       1
5214  3514.0       1
      8424.0       1
5285  2991.0       1
Length: 1012, dtype: int64

cell  hour_year
988   7991.0       1
1061  96.0         1
      118.0        1
      7463.0       1
1062  4793.0       1
                  ..
5001  5131.0       1
5066  7942.0       1
5141  3777.0       1
      6575.0       1
5214  7845.0       1
Length: 937, dtype: int64

cell  hour_year
628   6578.0       1
988   4795.0       1
1061  1777.0       1
1349  5376.0       1
1494  2374.0       1
                  ..
4991  519.0        1
      7883.0       1
5001  6874.0       1
5213  4317.0       1
5214  4094.0       1
Length: 538, dtype: int64

cell  hour_year
1277  7390.0       1
1784  1156.0       1
      7796.0       1
1928  7961.0       1
1929  7560.0       1
                  ..
5067  697.0        1
5138  1223.0       1
5140  2036.0       1
5211  919.0        1
5212  5464.0       1
Length: 458, dtype: int64

cell  hour_year
339   3890.0       1
628   7753.0       1
1349  4345.0       1
1353  1188.0       1
1784  5638.0       1
                  ..
5211  5040.0       1
5212  8736.0       1
5214  2585.0       1
      5914.0       1
5285  2836.0       1
Length: 343, dtype: int64

cell  hour_year
120   5597.0       1
340   1770.0       1
484   2276.0       1
844   496.0        1
916   356.0        1
                  ..
4994  8274.0       1
5001  3913.0       1
5065  6427.0       1
5213  8490.0       1
5285  2901.0       1
Length: 502, dtype: int64