In [66]:
import pandas as pd

df_crimes = pd.read_csv(
    "./output/maceio/maceio_with_grid_index.csv",
    delimiter=";",
    parse_dates=["DATA_HORA"]
)

In [67]:
display(df_crimes)
df_crimes.info()
years = sorted(df_crimes['DATA_HORA'].dt.year.unique())
display(years)

,Unnamed: 0,LONGITUDE,LATITUDE,ROUBO_GROUP,DATA_HORA,CIDADE_FATO,cell
0,0,-35.698388,-9.658217,street_robbery,2022-01-01 02:00:00,Maceió,825
1,1,-35.703405,-9.660662,street_robbery,2022-01-01 02:00:00,Maceió,863
2,2,-35.710142,-9.653007,vehicle_robbery,2022-01-01 02:00:00,Maceió,903
3,3,-35.713147,-9.668955,street_robbery,2022-01-01 03:00:00,Maceió,902
4,4,-35.703983,-9.663635,street_robbery,2022-01-01 04:00:00,Maceió,863
...,...,...,...,...,...,...,...
72707,72707,-35.756315,-9.662037,street_robbery,2014-12-22 12:50:00,Maceió,1175
72708,72708,-35.715706,-9.652401,vehicle_robbery,2014-12-22 19:00:00,Maceió,903
72709,72709,-35.755908,-9.586733,residential_robbery,2014-12-23 05:30:00,Maceió,1184
72710,72710,-35.738317,-9.624963,street_robbery,2014-12-23 09:30:00,Maceió,1063
72711,72711,-35.739418,-9.630707,vehicle_robbery,2014-12-23 15:00:00,Maceió,1062

<class 'pandas.DataFrame'>
RangeIndex: 72712 entries, 0 to 72711
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   72712 non-null  int64
 1   LONGITUDE    72712 non-null  float64
 2   LATITUDE     72712 non-null  float64
 3   ROUBO_GROUP  72712 non-null  str
 4   DATA_HORA    72712 non-null  datetime64[us]
 5   CIDADE_FATO  72712 non-null  str
 6   cell         72712 non-null  int64
dtypes: datetime64[us](1), float64(2), int64(2), str(2)
memory usage: 3.9 MB

[np.int32(2012),
 np.int32(2013),
 np.int32(2014),
 np.int32(2015),
 np.int32(2016),
 np.int32(2017),
 np.int32(2018),
 np.int32(2019),
 np.int32(2020),
 np.int32(2021),
 np.int32(2022)]

In [68]:
crimes_types = sorted(df_crimes['ROUBO_GROUP'].unique())
display(crimes_types)

['commercial_robbery',
 'public_transport_robbery',
 'residential_robbery',
 'street_robbery',
 'vehicle_robbery']

In [69]:
import numpy as np
import datetime
from pandarallel import pandarallel
import os

cpu_count = os.cpu_count() or 1
nb_workers = max(1, min(cpu_count, 24))
pandarallel.initialize(nb_workers=nb_workers, progress_bar=True)


def hour_of_year(dt):
    beginning_of_year = datetime.datetime(
        dt["DATA_HORA"].year, 1, 1, tzinfo=dt["DATA_HORA"].tzinfo
    )
    return pd.Series(
        {
            "hour_year": (dt["DATA_HORA"] - beginning_of_year).total_seconds()
            // 3600
        }
    )


df_crimes
display("Translate date of crime to hour of the year")
df_hour = df_crimes.merge(
    df_crimes.parallel_apply(hour_of_year, axis=1), left_index=True, right_index=True
)
display("Initial shape: ", df_hour.shape)
display("Initial shape: ", df_hour)

INFO: Pandarallel will run on 24 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.

'Translate date of crime to hour of the year'

VBox(children=(HBox(children=(IntProgress(value=0, description='0.00%', max=3030), Label(value='0 / 3030'))), …

'Initial shape: '

(72712, 8)

'Initial shape: '

,Unnamed: 0,LONGITUDE,LATITUDE,ROUBO_GROUP,DATA_HORA,CIDADE_FATO,cell,hour_year
0,0,-35.698388,-9.658217,street_robbery,2022-01-01 02:00:00,Maceió,825,2.0
1,1,-35.703405,-9.660662,street_robbery,2022-01-01 02:00:00,Maceió,863,2.0
2,2,-35.710142,-9.653007,vehicle_robbery,2022-01-01 02:00:00,Maceió,903,2.0
3,3,-35.713147,-9.668955,street_robbery,2022-01-01 03:00:00,Maceió,902,3.0
4,4,-35.703983,-9.663635,street_robbery,2022-01-01 04:00:00,Maceió,863,4.0
...,...,...,...,...,...,...,...,...
72707,72707,-35.756315,-9.662037,street_robbery,2014-12-22 12:50:00,Maceió,1175,8532.0
72708,72708,-35.715706,-9.652401,vehicle_robbery,2014-12-22 19:00:00,Maceió,903,8539.0
72709,72709,-35.755908,-9.586733,residential_robbery,2014-12-23 05:30:00,Maceió,1184,8549.0
72710,72710,-35.738317,-9.624963,street_robbery,2014-12-23 09:30:00,Maceió,1063,8553.0
72711,72711,-35.739418,-9.630707,vehicle_robbery,2014-12-23 15:00:00,Maceió,1062,8559.0

In [ ]:
GRID_SIZE = 39

for ct in crimes_types:
    df_per_crime = df_hour[df_hour["ROUBO_GROUP"] == ct].copy()
    df_all_years_list = []
    for y in years:
        dfy = df_per_crime[df_per_crime["DATA_HORA"].dt.year == y].copy()

        # count crimes by (cell, DATA_HORA)
        counts = dfy.groupby(["cell", "hour_year"]).size()
        display(counts)

        grid = counts.unstack("hour_year") 


        beginning_of_y1 = datetime.datetime(y, 1, 1)
        beginning_of_y2 = datetime.datetime(y+1, 1, 1)
        num_hours_total = int((beginning_of_y2 - beginning_of_y1).total_seconds() // 3600)
        grid = grid.reindex(columns=range(num_hours_total))
        grid = grid.reindex(index=range(GRID_SIZE**2))
        df_year = grid.copy()
        df_year.columns = list(map(lambda x: str(x) + f"_{str(y)}", df_year.columns.tolist()))
        df_all_years_list.append(df_year)

  
    df_all = pd.concat(df_all_years_list,axis=1)
    df_all.T.to_csv(f"./output/maceio/maceio_{ct}_all_grid.csv")

cell  hour_year
370   6891.0       1
722   963.0        1
      1443.0       1
      4035.0       1
      4923.0       1
                  ..
1307  1587.0       1
      1971.0       1
      6171.0       1
1384  579.0        1
      4059.0       1
Length: 365, dtype: int64

cell  hour_year
103   5857.0       1
180   6964.0       1
255   3984.0       1
      4297.0       1
524   7493.0       1
                  ..
1346  5395.0       1
      7285.0       1
1381  6781.0       1
      7910.0       1
1418  1054.0       1
Length: 808, dtype: int64

cell  hour_year
218   6865.0       1
523   825.0        1
561   107.0        1
      8414.0       1
599   6429.0       1
                  ..
1385  1096.0       1
1418  1717.0       1
1423  2175.0       1
1424  1984.0       1
      4118.0       1
Length: 601, dtype: int64

cell  hour_year
179   973.0        1
293   3265.0       1
      8737.0       1
561   6927.0       1
599   7099.0       1
                  ..
1381  4034.0       1
      5736.0       1
1384  5106.0       1
1418  522.0        1
1424  6625.0       1
Length: 310, dtype: int64

cell  hour_year
103   4316.0       1
294   117.0        1
524   5611.0       1
562   2830.0       1
      2974.0       1
                  ..
1384  6228.0       1
      8566.0       1
1385  4461.0       1
      8708.0       1
1497  7837.0       1
Length: 334, dtype: int64

cell  hour_year
255   1794.0       1
562   2441.0       1
      7582.0       1
825   1382.0       1
      3755.0       1
                  ..
1345  7319.0       1
1382  8125.0       1
1385  3563.0       1
      8643.0       1
1419  7485.0       1
Length: 249, dtype: int64

cell  hour_year
370   3095.0       1
752   1525.0       1
790   578.0        1
827   70.0         1
828   1384.0       1
                  ..
1346  4509.0       1
1381  569.0        1
1383  6229.0       1
1424  4679.0       1
      8523.0       1
Length: 196, dtype: int64

cell  hour_year
825   1801.0       1
826   2271.0       1
      3327.0       1
863   8404.0       1
      8435.0       1
                  ..
1381  7317.0       1
1383  3227.0       1
1384  4285.0       1
1385  2682.0       1
      7533.0       1
Length: 173, dtype: int64

cell  hour_year
600   2562.0       1
638   5132.0       1
828   624.0        1
865   6748.0       1
      6772.0       1
                  ..
1345  7094.0       1
      7580.0       1
1382  6372.0       1
1383  6564.0       1
1384  7428.0       1
Length: 93, dtype: int64

cell  hour_year
142   1253.0       1
752   979.0        1
824   3864.0       1
      4870.0       1
      7481.0       1
                  ..
1346  8173.0       1
1381  2376.0       1
1383  4217.0       1
1384  2369.0       1
      4674.0       1
Length: 178, dtype: int64

cell  hour_year
599   7531.0       1
825   243.0        1
      411.0        1
      508.0        1
      8280.0       1
                  ..
1346  3498.0       1
      4645.0       1
1381  1026.0       1
1382  4304.0       1
1385  7722.0       1
Length: 99, dtype: int64

cell  hour_year
332   3987.0       1
370   1299.0       1
714   1203.0       1
722   363.0        1
      435.0        1
                  ..
1420  6627.0       1
      7971.0       1
1497  1995.0       1
      5523.0       1
      7011.0       1
Length: 623, dtype: int64

cell  hour_year
103   7340.0       1
255   5952.0       1
294   5786.0       1
332   5442.0       1
523   7029.0       1
                  ..
1458  8470.0       1
1459  7166.0       1
1497  5241.0       1
      7101.0       1
1498  3875.0       1
Length: 1005, dtype: int64

cell  hour_year
103   382.0        1
      5829.0       1
179   1601.0       1
      5857.0       1
      6767.0       1
                  ..
1418  5687.0       1
1424  1798.0       1
1457  235.0        1
1458  6937.0       1
1497  2784.0       1
Length: 1205, dtype: int64

cell  hour_year
103   2519.0       1
179   1827.0       1
      7339.0       1
217   6614.0       1
      6619.0       1
                  ..
1384  7152.0       1
1418  217.0        1
1424  3742.0       1
      6909.0       1
      7125.0       1
Length: 784, dtype: int64

cell  hour_year
65    2445.0       1
179   4485.0       1
523   2570.0       1
      5959.0       1
524   2092.0       1
                  ..
1418  8556.0       1
1424  1960.0       1
      4196.0       1
1457  3145.0       1
1458  6374.0       1
Length: 1136, dtype: int64

cell  hour_year
255   2710.0       1
447   96.0         1
      1490.0       1
485   601.0        1
523   6262.0       1
                  ..
1382  3127.0       1
1385  2349.0       1
1418  2349.0       1
      6424.0       1
1498  8755.0       1
Length: 534, dtype: int64

cell  hour_year
447   1458.0       1
524   5111.0       1
561   1840.0       1
599   1213.0       1
      2276.0       1
                  ..
1381  7152.0       1
1384  5278.0       1
1418  1959.0       1
      5594.0       1
1424  6403.0       1
Length: 339, dtype: int64

cell  hour_year
447   7809.0       1
638   7344.0       1
715   4030.0       1
752   2135.0       1
865   572.0        1
                  ..
1380  7108.0       1
1381  5962.0       1
1382  4941.0       1
1384  375.0        1
1459  5916.0       1
Length: 109, dtype: int64

cell  hour_year
945   2126.0       1
980   512.0        1
      2099.0       1
      2194.0       1
      7776.0       1
981   10.0         1
      1198.0       1
      1582.0       1
983   3395.0       1
987   1800.0       1
1019  8401.0       1
      8449.0       1
      8760.0       1
1020  2292.0       2
      8569.0       1
1021  1247.0       1
1023  519.0        1
      1360.0       1
1024  1271.0       1
1057  2254.0       1
1058  2087.0       1
      2133.0       1
      2137.0       1
      8544.0       1
      8688.0       1
1059  2061.0       2
      2113.0       1
1061  769.0        1
1065  109.0        1
      3575.0       1
1068  418.0        1
1097  1968.0       1
      2296.0       1
1100  1290.0       1
1101  1605.0       1
1135  2443.0       1
1175  1760.0       1
      3130.0       1
1222  1273.0       1
1303  322.0        1
1341  679.0        1
      937.0        1
1383  888.0        1
      5888.0       1
dtype: int64

cell  hour_year
904   1079.0       1
      1223.0       1
      6599.0       1
943   7602.0       1
981   912.0        1
      1129.0       1
1018  4941.0       1
1019  48.0         1
      697.0        1
      908.0        1
      983.0        1
      1031.0       1
      1369.0       2
      1679.0       1
      7626.0       1
      8470.0       1
1020  5147.0       1
1021  5087.0       1
      5133.0       1
1033  6479.0       1
1058  1031.0       1
      1750.0       1
1065  4911.0       1
1066  1920.0       1
1068  6023.0       1
1097  1008.0       2
      1824.0       1
1175  1848.0       1
      3385.0       1
1183  5177.0       1
1223  5560.0       1
dtype: int64

cell  hour_year
902   6563.0       1
      8341.0       1
905   8173.0       1
914   4654.0       1
944   5218.0       1
948   7859.0       1
952   1496.0       1
954   7371.0       1
992   8182.0       1
      8220.0       1
1019  716.0        1
      6830.0       1
      8556.0       1
1058  1638.0       1
      4164.0       1
1064  8701.0       1
1065  132.0        1
      8373.0       1
1099  7982.0       1
1104  273.0        1
1108  4541.0       1
1144  4915.0       1
1185  8699.0       1
1344  8676.0       1
1381  8455.0       1
1498  4573.0       1
dtype: int64

cell  hour_year
601   4467.0       1
717   4059.0       1
      8739.0       1
722   3555.0       1
      5883.0       1
                  ..
1185  8043.0       1
1228  2523.0       1
1264  1107.0       1
      1731.0       1
      4611.0       1
Length: 113, dtype: int64

cell  hour_year
255   2704.0       1
752   7821.0       1
789   7465.0       1
790   7839.0       1
791   3661.0       1
                  ..
1346  2518.0       1
1381  491.0        1
1385  340.0        1
      3520.0       1
      5827.0       1
Length: 161, dtype: int64

cell  hour_year
562   6358.0       1
791   8290.0       1
825   6093.0       1
      7075.0       1
827   2359.0       1
                  ..
1345  7740.0       1
1346  314.0        1
      6782.0       1
      7236.0       1
1385  3075.0       1
Length: 132, dtype: int64

cell  hour_year
485   5403.0       1
790   288.0        1
824   4431.0       1
828   2560.0       1
864   4535.0       1
                  ..
1345  8484.0       1
      8577.0       1
      8624.0       1
1384  8241.0       1
1458  7212.0       1
Length: 94, dtype: int64

cell  hour_year
103   610.0        1
293   662.0        1
524   2231.0       1
600   20.0         1
      1251.0       1
                  ..
1345  6093.0       1
      6681.0       1
1346  1653.0       1
      7220.0       1
1385  1552.0       1
Length: 123, dtype: int64

cell  hour_year
255   5206.0       1
599   7353.0       1
601   7143.0       1
714   373.0        1
752   374.0        1
                  ..
1380  1065.0       1
1383  3536.0       1
      4092.0       1
1384  743.0        1
1423  4239.0       1
Length: 83, dtype: int64

cell  hour_year
294   3022.0       1
600   1201.0       1
638   3069.0       1
      4641.0       1
639   2563.0       1
                  ..
1383  8089.0       1
1384  3096.0       1
1385  8159.0       1
1419  6645.0       1
1424  4647.0       1
Length: 133, dtype: int64

cell  hour_year
218   5926.0       1
639   7284.0       1
715   3000.0       2
755   2871.0       1
791   7581.0       1
                  ..
1380  4844.0       1
1381  297.0        1
      2189.0       1
      5841.0       1
1458  3606.0       1
Length: 75, dtype: int64

cell  hour_year
639   724.0        1
827   1225.0       1
868   7446.0       1
873   511.0        1
902   471.0        1
914   2093.0       1
915   2638.0       1
940   5167.0       1
941   7238.0       1
944   5978.0       1
952   839.0        1
      2377.0       1
      7032.0       1
      7943.0       1
953   7389.0       1
992   1435.0       1
      1941.0       1
      2282.0       1
1020  3485.0       1
1061  856.0        1
1068  7675.0       1
1097  62.0         1
      461.0        1
1099  7373.0       1
1110  7943.0       1
1111  2811.0       1
      8690.0       1
1135  6534.0       1
1142  1777.0       1
1147  2926.0       1
1150  5362.0       1
      7898.0       1
      8718.0       1
1176  298.0        1
      462.0        1
1180  3185.0       1
1184  2407.0       1
1185  1774.0       1
      7840.0       1
1215  7222.0       1
1261  575.0        1
1262  338.0        1
1307  5596.0       1
1342  919.0        1
      8620.0       1
1345  448.0        1
1346  7062.0       1
      8017.0       1
1381  7919.0       1
1385  6908.0       1
1386  1254.0       1
1419  1003.0       1
      2023.0       2
dtype: int64

cell  hour_year
561   2159.0       1
865   7373.0       1
906   4232.0       1
907   1479.0       1
914   4319.0       1
      4750.0       1
940   1576.0       1
941   1103.0       1
      1750.0       1
942   3825.0       1
945   677.0        1
      3768.0       1
947   3741.0       1
948   5186.0       1
952   1014.0       1
      5614.0       1
954   384.0        1
      1918.0       1
980   670.0        1
985   4256.0       1
992   2925.0       1
      7846.0       1
993   385.0        1
      5279.0       1
1022  7231.0       1
1032  7830.0       1
1065  573.0        1
1070  2818.0       1
1072  1590.0       1
1098  5023.0       1
1110  5560.0       1
      8720.0       1
1135  748.0        1
1136  2999.0       1
1146  1426.0       1
1175  2781.0       1
1176  2008.0       2
      6829.0       1
1180  92.0         1
      5652.0       1
1184  4750.0       1
1185  1822.0       1
      5943.0       1
1214  1241.0       1
1215  6293.0       1
1223  8181.0       1
1224  645.0        1
1228  2805.0       1
1250  7566.0       1
1261  3330.0       1
1262  6293.0       1
1263  5938.0       1
1267  4647.0       1
1300  4798.0       1
1301  3084.0       1
1341  1962.0       1
      2312.0       1
1346  6796.0       1
1381  5989.0       1
1385  3479.0       1
dtype: int64

cell  hour_year
524   4889.0       1
638   3032.0       1
828   1018.0       1
906   4963.0       1
      5322.0       1
907   1943.0       1
913   8195.0       1
914   6284.0       1
943   2019.0       1
951   6475.0       1
      7532.0       1
952   5180.0       1
      6141.0       1
953   2215.0       1
      6764.0       1
954   4113.0       1
      5812.0       1
985   2101.0       1
      8178.0       1
991   3926.0       1
992   3548.0       1
993   6.0          1
      2066.0       1
      3764.0       1
994   4694.0       1
1031  3285.0       1
1058  5899.0       1
1059  1748.0       1
1065  5345.0       1
1097  2628.0       1
1136  3932.0       1
1145  5459.0       1
1149  4292.0       1
1150  2185.0       1
1175  4780.0       1
1176  2458.0       1
1184  6843.0       1
1185  3082.0       1
1186  4780.0       2
1213  1326.0       1
1222  594.0        1
1228  1846.0       1
      6856.0       1
1306  2513.0       1
1341  1209.0       1
      6166.0       1
1497  7209.0       1
dtype: int64

cell  hour_year
216   795.0        1
      7635.0       1
217   5139.0       1
561   5835.0       1
562   8091.0       2
                  ..
1424  3147.0       1
      3795.0       1
      4635.0       1
1497  195.0        2
      5163.0       1
Length: 2880, dtype: int64

cell  hour_year
103   2234.0       1
      7503.0       1
178   8540.0       1
179   8370.0       1
217   3180.0       1
                  ..
1424  4970.0       1
      7448.0       1
      7650.0       1
1458  5447.0       1
1498  6304.0       1
Length: 3949, dtype: int64

cell  hour_year
103   7583.0       1
178   856.0        1
218   6756.0       1
      7432.0       1
293   2420.0       1
                  ..
1425  7904.0       1
1458  2667.0       1
      4895.0       1
      6284.0       1
1497  4821.0       1
Length: 4953, dtype: int64

cell  hour_year
25    2417.0       1
179   1964.0       1
      8169.0       1
217   8448.0       1
218   4347.0       1
                  ..
1424  4509.0       1
      4655.0       1
      8300.0       1
1498  5313.0       1
      8125.0       1
Length: 5019, dtype: int64

cell  hour_year
25    3231.0       1
      3255.0       1
140   1911.0       1
141   839.0        1
179   2392.0       1
                  ..
1497  6392.0       1
      7368.0       1
      7967.0       1
      8768.0       1
1498  2481.0       1
Length: 6071, dtype: int64

cell  hour_year
63    8348.0       1
103   2736.0       1
      6361.0       1
179   4770.0       1
      7280.0       1
                  ..
1497  5436.0       1
      7579.0       1
      7654.0       1
1498  5632.0       1
      7755.0       1
Length: 6531, dtype: int64

cell  hour_year
103   37.0         1
      327.0        1
      7752.0       1
141   4792.0       1
      6253.0       1
                  ..
1498  3999.0       1
      4790.0       1
      5370.0       1
      6897.0       1
      7913.0       1
Length: 6405, dtype: int64

cell  hour_year
64    4551.0       1
103   3329.0       1
      8160.0       1
141   6536.0       1
179   8377.0       1
                  ..
1459  6022.0       1
      8720.0       1
1497  5927.0       1
      6373.0       1
1498  4545.0       1
Length: 5008, dtype: int64

cell  hour_year
64    776.0        1
102   5609.0       1
103   8011.0       1
141   776.0        1
179   1544.0       2
                  ..
1497  1057.0       1
      1572.0       1
      2204.0       1
      2360.0       1
1498  560.0        1
Length: 3661, dtype: int64

cell  hour_year
64    2223.0       1
103   311.0        1
      3256.0       1
179   2115.0       1
      3452.0       1
                  ..
1425  4722.0       1
1497  2743.0       1
      4561.0       1
      7215.0       1
      8750.0       1
Length: 2930, dtype: int64

cell  hour_year
103   1359.0       1
179   3445.0       1
254   8461.0       1
294   4976.0       1
      6320.0       1
                  ..
1459  6104.0       1
1497  3720.0       1
      4688.0       1
      5867.0       1
      6746.0       1
Length: 2930, dtype: int64

cell  hour_year
216   1923.0       1
      2379.0       1
      2739.0       1
      4707.0       1
255   8115.0       1
                  ..
1420  4035.0       1
      4275.0       1
      4515.0       1
1421  7611.0       1
1459  2907.0       1
Length: 1500, dtype: int64

cell  hour_year
103   3410.0       1
      5206.0       1
216   1840.0       1
218   8685.0       1
255   988.0        1
                  ..
1459  2712.0       1
1497  277.0        1
      1513.0       1
      8421.0       1
1498  6684.0       1
Length: 1526, dtype: int64

cell  hour_year
25    5756.0       1
64    3334.0       1
65    2014.0       1
103   938.0        1
179   3648.0       1
                  ..
1458  3082.0       1
      6979.0       1
1497  2206.0       1
      3237.0       1
1498  6112.0       1
Length: 1532, dtype: int64

cell  hour_year
64    5540.0       1
65    672.0        1
103   7027.0       1
      7269.0       1
179   2052.0       1
                  ..
1424  8422.0       1
      8542.0       1
1497  7344.0       1
1498  3405.0       1
      5341.0       1
Length: 1057, dtype: int64

cell  hour_year
103   7851.0       1
178   3740.0       1
255   8660.0       1
294   5426.0       1
      8321.0       1
                  ..
1424  8700.0       1
1458  3158.0       1
      3838.0       1
      6745.0       1
1497  6360.0       1
Length: 1215, dtype: int64

cell  hour_year
179   5212.0       1
218   3959.0       1
254   8346.0       1
293   1866.0       2
408   1512.0       1
                  ..
1497  1993.0       1
      2991.0       1
      6648.0       1
1498  3514.0       1
      8424.0       1
Length: 1012, dtype: int64

cell  hour_year
293   96.0         1
      7463.0       1
      7991.0       1
294   118.0        1
      4793.0       1
                  ..
1424  7605.0       1
      8084.0       1
1459  3777.0       1
      6575.0       1
1498  7845.0       1
Length: 936, dtype: int64

cell  hour_year
179   6578.0       1
293   4795.0       1
294   1777.0       1
370   5376.0       1
447   2374.0       1
                  ..
1424  2746.0       1
      3810.0       1
      8331.0       1
1498  4094.0       1
      4317.0       1
Length: 538, dtype: int64

cell  hour_year
370   7390.0       1
524   1156.0       1
      7796.0       1
562   7560.0       1
      7961.0       1
                  ..
1458  2160.0       1
1459  697.0        1
      2036.0       1
1497  919.0        1
      5464.0       1
Length: 456, dtype: int64

cell  hour_year
103   3890.0       1
179   7753.0       1
372   1188.0       1
409   4345.0       1
523   3250.0       1
                  ..
1497  5040.0       1
      8736.0       1
1498  2585.0       1
      2836.0       1
      5914.0       1
Length: 343, dtype: int64

cell  hour_year
25    5597.0       1
103   1770.0       1
141   2276.0       1
217   496.0        1
255   356.0        1
                  ..
1424  1700.0       1
      2418.0       1
      7645.0       1
1497  2901.0       1
1498  8490.0       1
Length: 500, dtype: int64